version: '3.1'

services:

  database:
    image: mongo
    container_name: 'happy-dinner-db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'